### PR TITLE
Fix for deprecation warning in rails 7

### PR DESCRIPTION
**Pull request by bunnahabhain**
Rails 7 gives the following deprecation warning:

DEPRECATION WARNING: `ActiveRecord::Base.partial_writes=` is deprecated and will be removed in Rails 7.1. Use `partial_updates=` and `partial_inserts=` instead. (called from <class:SelfCleaningSession> at /Users/david/RubymineProjects/limited_sessions/lib/limited_sessions/self_cleaning_session.rb:5)

The pull request clears the warning.

### CODE REVIEW

**Comment by zarqman** [comment]
Thanks so much for catching this and for the PR!

It seems like this change will break backwards compatibility with versions of Rails prior to v7. Unless you believe otherwise, perhaps a conditional could be added to maintain that compatibility?

**Comment by bunnahabhain** [comment]
You are absolutely right! This is my first attempt at a contribution to an open source project, and I jumped the gun.

**Comment by bunnahabhain** [comment]
I have added a conditional, and tested with both Rails versions 6.1.6.1 and 7.0.3. It appears to work properly with both versions. Hopefully, I have got it right this time.

**Comment by zarqman** [comment]
Looks good! Honored that you'd make your first opensource contribution to this project.  Thanks so much!

**Comment by bunnahabhain** [comment]
Fantastic. And thank you for this wonderfully useful Gem!

**Pull request merged**
